// AUTO-GENERATED from backend/app/data/*.csv — offline demo dataset.
// Keeps the frontend fully functional when the FastAPI backend is not running.
import { Robot } from '../models/battlebots.models';

export const DEMO_ROBOTS: Robot[] = [
  { robot: "Tombstone", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 33, losses: 13, ko_wins: 24, builder: "Ray Billings", country: "USA" },
  { robot: "Bite Force", weapon_type: "drum_spinner", weight_lb: 250, wins: 20, losses: 4, ko_wins: 9, builder: "Paul Ventimiglia", country: "USA" },
  { robot: "Minotaur", weapon_type: "drum_spinner", weight_lb: 250, wins: 26, losses: 12, ko_wins: 14, builder: "Daniel Freitas", country: "Brazil" },
  { robot: "Witch Doctor", weapon_type: "vertical_spinner", weight_lb: 250, wins: 29, losses: 15, ko_wins: 12, builder: "Andrea Suarez", country: "USA" },
  { robot: "End Game", weapon_type: "vertical_spinner", weight_lb: 250, wins: 27, losses: 7, ko_wins: 15, builder: "Jack Barker", country: "New Zealand" },
  { robot: "Hydra", weapon_type: "flipper", weight_lb: 250, wins: 21, losses: 13, ko_wins: 8, builder: "Jake Ewert", country: "USA" },
  { robot: "SawBlaze", weapon_type: "overhead_saw", weight_lb: 250, wins: 25, losses: 12, ko_wins: 10, builder: "Jamison Go", country: "USA" },
  { robot: "Copperhead", weapon_type: "drum_spinner", weight_lb: 250, wins: 18, losses: 11, ko_wins: 9, builder: "Zachary Lytle", country: "USA" },
  { robot: "Whiplash", weapon_type: "lifter", weight_lb: 250, wins: 22, losses: 10, ko_wins: 6, builder: "Matt Vasquez", country: "USA" },
  { robot: "Icewave", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 15, losses: 14, ko_wins: 9, builder: "Marco Meggiolaro", country: "USA" },
  { robot: "HUGE", weapon_type: "vertical_spinner", weight_lb: 250, wins: 14, losses: 12, ko_wins: 5, builder: "Jonathan Schultz", country: "USA" },
  { robot: "Yeti", weapon_type: "drum_spinner", weight_lb: 250, wins: 12, losses: 10, ko_wins: 7, builder: "Greg Gibson", country: "USA" },
  { robot: "Bronco", weapon_type: "flipper", weight_lb: 250, wins: 14, losses: 9, ko_wins: 6, builder: "Reason Bradley", country: "USA" },
  { robot: "Riptide", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 13, losses: 5, ko_wins: 8, builder: "Ethan Kurtz", country: "USA" },
  { robot: "Skorpios", weapon_type: "overhead_saw", weight_lb: 250, wins: 16, losses: 11, ko_wins: 7, builder: "Orion Beach", country: "USA" },
  { robot: "Hypershock", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 17, losses: 15, ko_wins: 11, builder: "Will Bales", country: "USA" },
  { robot: "Rotator", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 15, losses: 12, ko_wins: 7, builder: "Victor Soto", country: "USA" },
  { robot: "Lock-Jaw", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 16, losses: 16, ko_wins: 9, builder: "Donald Hutson", country: "USA" },
  { robot: "Blip", weapon_type: "flipper", weight_lb: 250, wins: 17, losses: 6, ko_wins: 5, builder: "Aren Hill", country: "USA" },
  { robot: "Valkyrie", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 13, losses: 10, ko_wins: 7, builder: "Leanne Cushing", country: "USA" },
  { robot: "Cobalt", weapon_type: "vertical_spinner", weight_lb: 250, wins: 14, losses: 8, ko_wins: 8, builder: "Dave Moulds", country: "UK" },
  { robot: "Fusion", weapon_type: "vertical_spinner", weight_lb: 250, wins: 10, losses: 7, ko_wins: 6, builder: "Jack Barker", country: "New Zealand" },
  { robot: "Black Dragon", weapon_type: "drum_spinner", weight_lb: 250, wins: 15, losses: 9, ko_wins: 5, builder: "Gabriel Felix", country: "Brazil" },
  { robot: "Uppercut", weapon_type: "vertical_spinner", weight_lb: 250, wins: 12, losses: 9, ko_wins: 6, builder: "Sam McAmis", country: "USA" },
  { robot: "Jager", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 9, losses: 8, ko_wins: 5, builder: "Kevin Milczewski", country: "USA" },
  { robot: "Free Shipping", weapon_type: "overhead_saw", weight_lb: 250, wins: 11, losses: 10, ko_wins: 4, builder: "Gary Gin", country: "USA" },
  { robot: "Shatter", weapon_type: "hammer", weight_lb: 250, wins: 13, losses: 11, ko_wins: 4, builder: "Adam Wrench", country: "USA" },
  { robot: "Gruff", weapon_type: "lifter", weight_lb: 250, wins: 12, losses: 7, ko_wins: 3, builder: "Sam Merrill", country: "USA" },
  { robot: "Hijinx", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 11, losses: 9, ko_wins: 5, builder: "Jennifer Herchenroeder", country: "USA" },
  { robot: "Tantrum", weapon_type: "vertical_spinner", weight_lb: 250, wins: 18, losses: 8, ko_wins: 7, builder: "Aaron Kohls", country: "USA" },
  { robot: "Big Dill", weapon_type: "lifter", weight_lb: 250, wins: 7, losses: 9, ko_wins: 2, builder: "Kevin Barker", country: "USA" },
  { robot: "Claw Viper", weapon_type: "lifter", weight_lb: 250, wins: 9, losses: 8, ko_wins: 3, builder: "Kevin Milczewski", country: "USA" },
  { robot: "Kraken", weapon_type: "crusher", weight_lb: 250, wins: 8, losses: 11, ko_wins: 3, builder: "Matt Spurk", country: "USA" },
  { robot: "Lucky", weapon_type: "flipper", weight_lb: 250, wins: 10, losses: 9, ko_wins: 4, builder: "Pablo Vasquez", country: "USA" },
  { robot: "Deep Six", weapon_type: "vertical_spinner", weight_lb: 250, wins: 6, losses: 9, ko_wins: 4, builder: "Jerry Clarkin", country: "USA" },
  { robot: "Captain Shrederator", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 8, losses: 15, ko_wins: 5, builder: "Brian Nave", country: "USA" },
  { robot: "Ghost Raptor", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 7, losses: 10, ko_wins: 4, builder: "Chuck Pitzer", country: "USA" },
  { robot: "Chomp", weapon_type: "hammer", weight_lb: 250, wins: 6, losses: 10, ko_wins: 3, builder: "Zoe Stephenson", country: "USA" },
  { robot: "Beta", weapon_type: "hammer", weight_lb: 250, wins: 9, losses: 8, ko_wins: 5, builder: "John Reid", country: "UK" },
  { robot: "Mammoth", weapon_type: "lifter", weight_lb: 250, wins: 5, losses: 10, ko_wins: 2, builder: "Peter Waller", country: "UK" },
  { robot: "Bombshell", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 10, losses: 10, ko_wins: 5, builder: "John Mladenik", country: "USA" },
  { robot: "Bloodsport", weapon_type: "horizontal_spinner", weight_lb: 250, wins: 8, losses: 9, ko_wins: 4, builder: "Justin Marple", country: "USA" },
];

export interface DemoMatch { season: number; robot_a: string; robot_b: string; winner: string; method: string; }

export const DEMO_MATCHES: DemoMatch[] = [
  { season: 2016, robot_a: "Tombstone", robot_b: "Witch Doctor", winner: "Tombstone", method: "KO" },
  { season: 2016, robot_a: "Bombshell", robot_b: "Tombstone", winner: "Tombstone", method: "KO" },
  { season: 2016, robot_a: "Bronco", robot_b: "Icewave", winner: "Bronco", method: "JD" },
  { season: 2016, robot_a: "Ghost Raptor", robot_b: "Yeti", winner: "Yeti", method: "KO" },
  { season: 2018, robot_a: "Minotaur", robot_b: "Witch Doctor", winner: "Minotaur", method: "JD" },
  { season: 2018, robot_a: "Bite Force", robot_b: "Minotaur", winner: "Bite Force", method: "JD" },
  { season: 2018, robot_a: "Tombstone", robot_b: "Minotaur", winner: "Minotaur", method: "KO" },
  { season: 2018, robot_a: "Bite Force", robot_b: "Lock-Jaw", winner: "Bite Force", method: "KO" },
  { season: 2018, robot_a: "Hydra", robot_b: "Beta", winner: "Hydra", method: "JD" },
  { season: 2018, robot_a: "Captain Shrederator", robot_b: "Yeti", winner: "Yeti", method: "JD" },
  { season: 2018, robot_a: "Rotator", robot_b: "Lock-Jaw", winner: "Rotator", method: "JD" },
  { season: 2019, robot_a: "Bite Force", robot_b: "Tombstone", winner: "Bite Force", method: "JD" },
  { season: 2019, robot_a: "End Game", robot_b: "Witch Doctor", winner: "End Game", method: "KO" },
  { season: 2019, robot_a: "SawBlaze", robot_b: "Copperhead", winner: "SawBlaze", method: "JD" },
  { season: 2019, robot_a: "Bite Force", robot_b: "SawBlaze", winner: "Bite Force", method: "JD" },
  { season: 2019, robot_a: "Minotaur", robot_b: "Whiplash", winner: "Whiplash", method: "JD" },
  { season: 2019, robot_a: "Hydra", robot_b: "Rotator", winner: "Hydra", method: "KO" },
  { season: 2019, robot_a: "Icewave", robot_b: "Deep Six", winner: "Icewave", method: "KO" },
  { season: 2020, robot_a: "Bite Force", robot_b: "Whiplash", winner: "Bite Force", method: "JD" },
  { season: 2020, robot_a: "End Game", robot_b: "SawBlaze", winner: "End Game", method: "JD" },
  { season: 2020, robot_a: "Hydra", robot_b: "Rotator", winner: "Hydra", method: "KO" },
  { season: 2020, robot_a: "Witch Doctor", robot_b: "Hydra", winner: "Witch Doctor", method: "JD" },
  { season: 2020, robot_a: "Bite Force", robot_b: "Cobalt", winner: "Bite Force", method: "JD" },
  { season: 2020, robot_a: "Tombstone", robot_b: "Copperhead", winner: "Tombstone", method: "KO" },
  { season: 2020, robot_a: "Uppercut", robot_b: "HUGE", winner: "Uppercut", method: "JD" },
  { season: 2020, robot_a: "Jager", robot_b: "Gruff", winner: "Gruff", method: "JD" },
  { season: 2021, robot_a: "End Game", robot_b: "SawBlaze", winner: "End Game", method: "JD" },
  { season: 2021, robot_a: "Tombstone", robot_b: "Hypershock", winner: "Tombstone", method: "KO" },
  { season: 2021, robot_a: "Copperhead", robot_b: "Whiplash", winner: "Whiplash", method: "JD" },
  { season: 2021, robot_a: "Witch Doctor", robot_b: "Cobalt", winner: "Witch Doctor", method: "JD" },
  { season: 2021, robot_a: "Tantrum", robot_b: "Whiplash", winner: "Tantrum", method: "JD" },
  { season: 2021, robot_a: "Hydra", robot_b: "Shatter", winner: "Hydra", method: "JD" },
  { season: 2021, robot_a: "Blip", robot_b: "Lock-Jaw", winner: "Blip", method: "KO" },
  { season: 2021, robot_a: "Fusion", robot_b: "Rotator", winner: "Fusion", method: "KO" },
  { season: 2021, robot_a: "Black Dragon", robot_b: "Hijinx", winner: "Black Dragon", method: "JD" },
  { season: 2022, robot_a: "Riptide", robot_b: "Whiplash", winner: "Riptide", method: "KO" },
  { season: 2022, robot_a: "End Game", robot_b: "Copperhead", winner: "End Game", method: "JD" },
  { season: 2022, robot_a: "Tombstone", robot_b: "Skorpios", winner: "Tombstone", method: "KO" },
  { season: 2022, robot_a: "Minotaur", robot_b: "Hypershock", winner: "Minotaur", method: "JD" },
  { season: 2022, robot_a: "Riptide", robot_b: "Lock-Jaw", winner: "Riptide", method: "KO" },
  { season: 2022, robot_a: "Witch Doctor", robot_b: "Bloodsport", winner: "Witch Doctor", method: "KO" },
  { season: 2022, robot_a: "Tantrum", robot_b: "Hydra", winner: "Tantrum", method: "JD" },
  { season: 2022, robot_a: "Blip", robot_b: "Cobalt", winner: "Blip", method: "JD" },
  { season: 2022, robot_a: "SawBlaze", robot_b: "Valkyrie", winner: "SawBlaze", method: "JD" },
  { season: 2022, robot_a: "Copperhead", robot_b: "Kraken", winner: "Copperhead", method: "KO" },
  { season: 2023, robot_a: "Riptide", robot_b: "SawBlaze", winner: "SawBlaze", method: "JD" },
  { season: 2023, robot_a: "Witch Doctor", robot_b: "Whiplash", winner: "Witch Doctor", method: "JD" },
  { season: 2023, robot_a: "Hydra", robot_b: "HUGE", winner: "Hydra", method: "JD" },
  { season: 2023, robot_a: "Tombstone", robot_b: "Yeti", winner: "Tombstone", method: "KO" },
  { season: 2023, robot_a: "End Game", robot_b: "Minotaur", winner: "End Game", method: "KO" },
  { season: 2023, robot_a: "Copperhead", robot_b: "Hypershock", winner: "Hypershock", method: "KO" },
  { season: 2023, robot_a: "Tantrum", robot_b: "Cobalt", winner: "Tantrum", method: "JD" },
  { season: 2023, robot_a: "Blip", robot_b: "Black Dragon", winner: "Blip", method: "JD" },
  { season: 2023, robot_a: "Riptide", robot_b: "Hydra", winner: "Riptide", method: "KO" },
  { season: 2023, robot_a: "SawBlaze", robot_b: "Skorpios", winner: "SawBlaze", method: "JD" },
  { season: 2023, robot_a: "Lucky", robot_b: "Gruff", winner: "Gruff", method: "JD" },
  { season: 2024, robot_a: "End Game", robot_b: "Riptide", winner: "End Game", method: "JD" },
  { season: 2024, robot_a: "Minotaur", robot_b: "Hydra", winner: "Minotaur", method: "KO" },
  { season: 2024, robot_a: "Tombstone", robot_b: "Lock-Jaw", winner: "Tombstone", method: "KO" },
  { season: 2024, robot_a: "Witch Doctor", robot_b: "Tantrum", winner: "Witch Doctor", method: "JD" },
  { season: 2024, robot_a: "Hypershock", robot_b: "Blip", winner: "Hypershock", method: "JD" },
  { season: 2024, robot_a: "SawBlaze", robot_b: "Whiplash", winner: "SawBlaze", method: "JD" },
  { season: 2024, robot_a: "Copperhead", robot_b: "Valkyrie", winner: "Valkyrie", method: "JD" },
  { season: 2024, robot_a: "Cobalt", robot_b: "Uppercut", winner: "Cobalt", method: "KO" },
  { season: 2024, robot_a: "Riptide", robot_b: "Hypershock", winner: "Riptide", method: "KO" },
  { season: 2024, robot_a: "Bite Force", robot_b: "End Game", winner: "End Game", method: "JD" },
];
